[package]
name = "kitchen-central-kitchen"
version = "0.1.0"
description = "Central Kitchen kuhinjska tabla za porudzbine"
authors = ["Kubura"]
edition = "2021"

[lib]
name = "kitchen_central_kitchen_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
